# Site settings
title: I Hate Glob
description: >
  FUCK YOU DON'T PROGRAM IT LIKE THAT.
  PUT A SOCK IN IT.
  I REALLY MEAN IT THIS TIME
baseurl: ""
url: "http://stu.scot"
timezone: "Europe/London"
permalink: /glob/:year/:month/:day/:title/

# Build settings
markdown: kramdown
